# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
--- 
jobs: 
  build: 
    docker: 
      - 
        image: "python:3.7.3-stretch"
    steps: 
      - checkout
      - 
        keys: 
          - "v1-dependencies-{{ checksum \"requirements.txt\" }}"
          - v1-dependencies-
        restore_cache: ~
      - 
        command: |
            python3 -m venv venv
            . venv/bin/activate
            make install
            # Install hadolint
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x /bin/hadolint
        name: "install dependencies"
        run: ~
      - 
        key: "v1-dependencies-{{ checksum \"requirements.txt\" }}"
        paths: 
          - ./venv
        save_cache: ~
      - 
        command: |-
            . venv/bin/activate
            make lint
        name: "run lint"
        run: ~
    working_directory: ~/repo
version: 2

